config/opendatahub-io/org.yaml
The PR will deprecate the `Developers` and `Dev Leads` teams in the opendatahub-io organization.  
This change will not remove them from the organization immediately but it will prevent changes to the team by `peribolos` when the org.yaml file is updated
Closes #3
=> Deprecate the Developers and Dev Leads teams

config/opendatahub-io/org.yaml
In support of #4 & #12, this PR creates a new `modelmesh respository Write` team to replace the `Developers` team with the same members and permissions
=> Create the modelmesh Repository Write team and add new users

config/opendatahub-io/org.yaml
In support of #4 & #12, this PR creates a new rest-proxy repository Write team to replace the Developers team with the same members and permissions
=> Create the restproxy Repository Write team and add new users

config/opendatahub-io/org.yaml
In support of #4 & #12, this PR creates a new `odh-model-controller respository Write` team to replace the Developers team with the same members and permissions
Replaces #1
=> Create the odh-model-controller Repository Write team and add new users

config/opendatahub-io/org.yaml
Get Triage access to the Notebook Controller
I would like to get Triage access being a reviewer of the notebook controller
https://github.com/opendatahub-io/kubeflow/blob/25375774972d399c77195ec1c9d8a5de47f0fcfc/OWNERS
=> Get Triage access to the Notebook Controller

config/opendatahub-io/org.yaml
Get Admin access to the Notebook Repo
I would like admin access to the notebook repo, being an approval and review of the component
https://github.com/opendatahub-io/notebooks/blob/main/OWNERS
=> Get Admin access to the Notebook Repo

config/opendatahub-io/org.yaml
Add a new team to the ODH org to give access to given repos for the active Service Mesh integration work.
No
=> Create Service Mesh Integration team

config/opendatahub-io/org.yaml
Adding a group for maintaining issues in https://github.com/opendatahub-io/opendatahub-community
/hold
I still need to add a few others... but I wanted to get this out before complicating things to see what the process is.
FWIW, the HOWTO doesn't link to the binary -- it's a relative link that doesn't go anywhere. https://github.com/opendatahub-io/org-management/blob/main/HOWTO.md#how-to-run-the-peribolos
=> Create ODH Community Maintainers

config/opendatahub-io/org.yaml
Add Jeff DeMoss and Karl Eklund, PMs, to the odh community so they can modify tracker tickets.
=> Add pms for odh community

config/opendatahub-io/org.yaml
Add sutaakar to org members and distributed workloads maintainers
=> Add sutaakar to org members and distributed workloads maintainers

config/opendatahub-io/org.yaml
Kyle needs access to update the tracker of trackers with the UX Lead.
Eg. https://github.com/opendatahub-io/opendatahub-community/issues/41
=> Add kywalker-rh to odh community maintainers

config/opendatahub-io/org.yaml
In order to maintain the TrustyAI Feature + Issue tracker for the ODH Projects page, I need the ability to create issues within odh-community, as per @andrewballantyne's suggestion.
=> Add Rob Geada to odh-community

config/opendatahub-io/org.yaml
Add etirelli to opendatahub-operator and opendatahub-community maintainers
=> Add etirelli to opendatahub-operator and opendatahub-community maintainers

.github/workflows/approval_check.yml
Reverts opendatahub-io/org-management#71
This secret shouldn't be required by the approval workflow.
=> Revert "Use org token for merge workflow"

config/opendatahub-io/org.yaml
We already have a kserve repo but it is not mentioned in our org-management. MLServing team will contribute to it and maintain it. The write access is also needed for GitHub Issues tracking purposes.
=> Create kserve team

config/opendatahub-io/org.yaml
Fixes an error when running peribolos due to members in the `Data Science Pipelines Maintainers` team existing as `maintainers` and `members`
=> Remove the duplicate maintainer & member from dsp maintainers

config/opendatahub-io/org.yaml
updating username from Red Hat account to Github account.
=> update username to Github account

config/opendatahub-io/org.yaml
to mlserving team
We had created new repo [caikit-tgis-serving](https://github.com/opendatahub-io/caikit-tgis-serving) into ODH. Model Serving team will maintain those. PR is requesting admin access to those repos for model serving team.
=> added new repo caikit-tgis-serving

config/opendatahub-io/org.yaml
Requesting Triage access so our team could manage issues related to ML Serving in non-ml-serving repos of ODH.
=> Add opendatahub-community to model serving team

config/opendatahub-io/org.yaml
Sharing ownership of each repo with the UX and UI Leads so we can manage our heavy inter-connectivity.
Already spoke to Kyle about this and he agreed.
=> Share ux UI lead ownership

config/opendatahub-io/org.yaml
Joined OpenShift AI QE team, requesting access as part of onboarding.
=> Add winklerm to org members and distributed workloads maintainers

config/opendatahub-io/org.yaml
Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>
Add israel-hdez to the list of AI Edge Maintainers
=> Add israel-hdez to AI Edge Maintainers

config/opendatahub-io/org.yaml
The `Model Registry Maintainers` team has a reference to the `model-registry` (#111) repo that does not exist which caused an error when syncing the file.
=> Remove non-existent model-registry repo

config/opendatahub-io/org.yaml
Add Isabella do Amaral (ID: @isinyaaa) to ODH org and as a member of the Model Registry team.
=> Add isinyaaa to odh-io and mlregistry team

config/opendatahub-io/org.yaml
Cleanup org groups to match the growing responsibilities of the Dashboard. 
Accompanying permissions in Dashboard: https://github.com/opendatahub-io/odh-dashboard/pull/1716
=> Shift dashboard owners

config/opendatahub-io/org.yaml
Fixes the peribolos error https://github.com/opendatahub-io/org-management/actions/runs/6025500339/job/16346335472
=> Remove andrewballantyne from members of ODH Dashboard Owners

config/opendatahub-io/org.yaml
Adding Gabriel Markley a Sr. Manager leading UI and IDE, to the admins section.
=> Add gmarkley-vi to opendatahub-io admins

config/opendatahub-io/org.yaml
Signed-off-by: heyselbi <selbi@redhat.com>
Removing mholder6 since not currently part of the ODH org
=> Remove mholder6 - not part of the org at the moment

config/opendatahub-io/org.yaml
Adding repository reference to model-registry for the Model Registry Maintainers team. 
=> Added model-registry repo to Model Registry Maintainers team

config/opendatahub-io/org.yaml
Adding Ramesh Reddy as a maintainer of the model-registry repo
- [x ] New members have reviewed and acknowledged the Open Data Hub:
- [ x] New members are added in alphabetical order
- [x ] Only one new member change per commit (if you add two members separate it in two commits
- [x ] For individual user changes: Commit message format `Add <USERNAME> to <opendatahub-io, mlops-sig, ...>`.
=> Add `rareddy` to model-registry

config/opendatahub-io/org.yaml
Adding Ajay Jaganathan (ID: ajaganat) to ODH org and as member of opendatahub.io, odh-manifests repository Contributors and ODH Operator Maintainers
=> Add ajaganat to opendatahub.io, odh-manifests repository Contributors and ODH Operator Maintainers

config/opendatahub-io/org.yaml
/assign @LaVLaS 
/cc @jeremyeder
=> Add jeremyeder as a maintainer of the architecture-decision-records repo

config/opendatahub-io/org.yaml
Dupe PR from #149 to fix merge blockers
=> Add jwforres as a maintainer of the architecture-decision-records repo

config/opendatahub-io/org.yaml
This commit makes following changes
- Remove user from Notebook maintainers list
- Add user as an admin for opendatahub.io repo
=> Update permissions for VaishnaviHire

config/opendatahub-io/org.yaml
Remove Vannten from org teams as he has moved on to a different role
=> Remove Vannten from org teams

config/opendatahub-io/org.yaml
Re-Adjust the Notebook teams to consolidate all work of notebooks
Instead of 2 separate team for notebook and kubeflow.
consolidating both into 1. 
Going further, we will only have notebook  maintainer (admin), and notebook devs (triage)
=> Clean-Up: Re-Adjust the Notebook teams to consolidate all work of notebooks

config/opendatahub-io/org.yaml
Need the power to fork repos to ODH, notably OVMS as we bring it up to date and in line with our build processes
=> Adding Xaenalt as maintainer for model serving

config/opendatahub-io/org.yaml
Need to maintain the DevOps App which has an immediate need for syncing all upstream github issues to the github board and would be needed for more such automation in future
=> Add dchourasia to opendatahub-io as an admin

config/opendatahub-io/org.yaml
Removing access to Dashboard. [This grants unnecessary access](https://github.com/opendatahub-io/org-management/commit/a71dc4ceb8fb02ad732d465007091dcc9f52a592) to the Dashboard component and I don't think it's needed.
cc @cam-garrison
=> Remove Service Mesh access to Dashboard

config/opendatahub-io/org.yaml
I recently joined the OpenShift AI project and will be working on OpenDataHub.
=> Add dgutride to opendatahub-io, odh-dashboard

config/opendatahub-io/org.yaml
Need to be in the opendatahub-io org to run "cherry-pick" bot in operator git repo.
=> Add zdtsw to opendatahub.io triage

config/opendatahub-io/org.yaml
Remove @LaVLaS from the notebook teams.  Also using this as a test of the peribolos github action
=> Remove LaVLaS from Notebook teams

config/opendatahub-io/org.yaml
Added caikit-tgis-client repo, need admin powers on it
=> Enable admin for caikit-tgis-client repo

config/opendatahub-io/org.yaml
Adding Laurentiu Bradin to ODH and ML Serving team
=> Add z103cb to opendatahub-io and ML Serving team

config/opendatahub-io/org.yaml
I am QE of Model Registry, for example @dhirajsb can confirm 😀 
=> Add rkubis to the opendatahub-io maintainers list

.github/workflows/apply-org-membership.yaml
There was a typo in the path used for the github action to trigger applying org membership in response to membership changes. This change fixes that typo so that the automation will be triggered when we want it to.
=> Use correct file path for github action trigger

config/organization_members.yaml
Eoin Gallinagh with username VanillaSpoon has left Red Hat and therefore should be removed from the org members.
=> Removing Eoin Gallinagh from org members

config/organization_members.yaml
Add adolfo-ab as a member of the opendatahub-io organization.
=> Add adolfo-ab to org members

config/organization_members.yaml
Related to: https://issues.redhat.com/browse/RHOAIENG-16580
This is a bot account of IDE team. The scope of this account is to use it in order to generate tokens to use in IDE repositories for GHA workflows.
=> Add @ide-developer on opendatahub-io org

config/organization_members.yaml
Remove @diegolovison from ODH org as he is moving to a new team.
I noticed @4n4nd was also still in the org. He hasn't been involved with ODH for a few years now so updating that.
=> Diego offboarding

config/organization_members.yaml
Add `opendatahub-tests-bot` which is used in https://github.com/opendatahub-io/opendatahub-tests CI
=> Add opendatahub-tests-bot to organization_members

config/organization_members.yaml
Removing org members that left RHOAI/ODH
More specifically removing the following members:
Matt Mahoney
Yauheni Kaliuta
Srijoni Biswas
Ajay Pratap
=> Remove from organization_members.yaml people no longer working in ODH

config/organization_members.yaml
Adds danijett-design as a member of the organization as requested by @dimakis
=> Add danijett-design to organization_members.yaml
