opendatahub-io/org-management

config/opendatahub-io/org.yaml

Create 3 new teams and add @LaVLaS , @VaishnaviHire, @harshad16 and @VannTen as members
- `odh-manifests repository Admin`
- `odh-manifests repository Contributors`
- `odh-manifests repository Triage`

Create odh-manifests teams and add initial members

---

config/opendatahub-io/org.yaml

Remove 4n4nd from teams AND add jbusche,tedhtchang to the org

---

config/opendatahub-io/org.yaml

On behalf of @kywalker-rh, adding @yannnz and @simrandhaliw to the opendatahub-io organization

Add simrandhaliw and yannnz to the odh organization

---

config/opendatahub-io/org.yaml

Add dimakis to org and distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Add `astefanutti` to organization members and distributed workloads maintainers.

Add astefanutti to org members and distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Add carsonmh to opendatahub-io, distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Add amsharma3 to organization members and distributed workloads maintainers.

Add amsharma3 to org members and distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Join notebook controller maintainer team with admin role
WOuld be helping out with the maintenance of the notebook controller going forward.

Join notebook controller maintainer team with admin role

---

.github/ISSUE_TEMPLATE/membership_request.yaml
.github/PULL_REQUEST_TEMPLATE.md
README.md

Adds PR and Issue template to outline the requirements for membership

Added PR and Issue templates

---

config/opendatahub-io/org.yaml

Add @ChughShilpa to org members and distributed workloads maintainers

Add ChughShilpa to org members and distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Welcome @dibryant to the project
She is a full time team member and has changed her older github id.
This replaces her old id with a new and includes her in notebooks team

Welcome @dibryant to the project

---

config/opendatahub-io/org.yaml

This team will be responsible for managing the org-management repo.

Create ODH org management team

---

config/opendatahub-io/org.yaml

Add xianli123 and yih-wang to opendatahub-io org

---

config/opendatahub-io/org.yaml

Raising this pr for similar reasons as https://github.com/opendatahub-io/org-management/pull/45 and https://github.com/opendatahub-io/org-management/pull/39

Add anishasthana to ODH Community Maintainers

---

config/opendatahub-io/org.yaml

Adding etirelli to opendatahub-io

Adding etirelli to opendatahub-io

---

config/opendatahub-io/org.yaml

Add Fiona-Waters to org and distributed workloads maintainers

---

config/opendatahub-io/org.yaml

Recently joined the distributed workloads team.

Add VanillaSpoon to org and distributed workloads maintainers

---

.github/build/main.py
.github/workflows/approval_check.yml

Update maintainers check to account for teams without maintainers

Add safe guard for teams without maintainers

---

.github/workflows/approval_check.yml

Add automerge capability

---

.github/workflows/merge_membership_pr.yml

Fix merge PR action

---

.github/workflows/merge_membership_pr.yml

Refer to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for additional context.

Correctly pass PR between workflows

---

config/opendatahub-io/org.yaml

Fix ordering of ODH Dashboard Maintainers

---

config/opendatahub-io/org.yaml

Request made by Alex Corvin
Kyle Walker and Vince Conzola

Ralombarwork

---

config/opendatahub-io/org.yaml

Add asansari to ODH Dashboard Maintainers

---

config/opendatahub-io/org.yaml

We recently forked three caikit repos (`caikit`, `caikit-nlp` and `caikit-tgis-backend`) and `text-generation-inference` repo into ODH. Model Serving team will maintain those. PR is requesting admin access to those repos for model serving team.

added recently forked caikit and tgi to mlserving team

---

config/opendatahub-io/org.yaml

Adding user ldimaggi

---

config/opendatahub-io/org.yaml

 Add zdtsw to opendatahub-operator

---

config/opendatahub-io/org.yaml

Joined OpenShift AI team, requesting access as part of onboarding

Add jwforres to opendatahub-io

---

config/opendatahub-io/org.yaml

Add christianvogt to opendatahub-io, ODH Dashboard Maintainers

---

config/opendatahub-io/org.yaml

add jeremyeder to opendatahub-io

---

config/opendatahub-io/org.yaml

Add biswassri to ODH org and Distributed Workload members

---

config/opendatahub-io/org.yaml

Creating a GitHub team to maintain the ai-edge repository

Create AI Edge maintainers team

---

config/opendatahub-io/org.yaml

Adding new user dhirajsb to opendatahub-io org
~~- [ ] For new team requests: Commit message format `Create <TEAMNAME>`. If the new team consists solely of existing members, you may~~
~~- [ ] New GitHub team requests are from an existing opendatahub-io member who will function as the maintainer of the team. Each additional member will follow the same requirements for adding new members~~

Add dhirajsb to opendatahub-io

---

config/opendatahub-io/org.yaml

Add rkpattnaik780 to opendatahub-io, Notebook Controller Triage members

---

config/opendatahub-io/org.yaml

Joined OpenShift AI team, requesting access as part of onboarding steps.

Add adelton to opendatahub-io

---

config/opendatahub-io/org.yaml

Add ppadti to opendatahub-io, ODH Dashboard Maintainers

---

config/opendatahub-io/org.yaml

Add dpanshug to opendatahub-io and ODH Dashboard Maintainers

---

config/opendatahub-io/org.yaml

Onboarding task
Onboarding task

Add tarilabs to opendatahub-io org

---

config/opendatahub-io/org.yaml

Creating new team for Model Registry component.
New team is under @taneem-ibrahim and Ramesh Reddy. Team members are @dhirajsb, @lampajr and @tarilabs

Create Model Registry Maintainers team

---

config/opendatahub-io/org.yaml

- [ x] New members are added in alphabetical order
- [ x] Only one new member change per commit (if you add two members separate it in two commits
- [ x] For individual user changes: Commit message format `Add <USERNAME> to <opendatahub-io, mlops-sig, ...>`.

Add rareddy to opendatahub-io

---

config/opendatahub-io/org.yaml

Joined OpenShift AI QE team, requesting access as part of onboarding.

Add Raghul-M to org members and distributed workloads member

---

config/opendatahub-io/org.yaml

I'm a new member of the Red Hat's Data Science Pipelines team.

Add hbelmiro to opendatahub-io, mlops-sig

---

config/opendatahub-io/org.yaml

Add Cat (as maintainer) & Gabe (as member) to the OpenDataHub-IO project.

Add cat and gabe

---

config/opendatahub-io/org.yaml

add dtrifiro to opendatahub-io, model-serving

---

config/opendatahub-io/org.yaml

Remove duplicate entry for gmarkley-vi

---

config/opendatahub-io/org.yaml

Adding a group for the UX designers. 

Add ux team

---

config/opendatahub-io/org.yaml

Add biswassri to AI Edge team

---

config/opendatahub-io/org.yaml

Add jackdelahunt to Ai Edge team

---

config/opendatahub-io/org.yaml

Add Cliodhna to the ODH Org
Add both Cliodhna & Rachel to the UX team

Update ux members

---

config/opendatahub-io/org.yaml

Add new team member Yauheni Kaliuta as a member of orgs.opendatahub-io.members

Add ykaliuta to opendatahub-io

---

config/opendatahub-io/org.yaml

Add diegolovison to org.yaml

---

config/opendatahub-io/org.yaml

Adding a new team with admin permission for the ai-edge repo

Create ai edge admins team

---

config/opendatahub-io/org.yaml

Adding @jackdelahunt to the org to unblock failures when running in peribolos

Add Jack Delahunt to the odh-io org

---

config/opendatahub-io/org.yaml

Correct the github user id for @AjayJagan 

Use the correct github username for Ajayjagan

---

config/opendatahub-io/org.yaml

Adding Rashmi Panchamukhi to ODH org and MLServing team

Add rpancham to opendatahub-io and mlserving team

---

config/opendatahub-io/org.yaml

I have joined the Operator Scrum Team on the RHODS/RHOAI Project.
@etirelli @VaishnaviHire 

Add asanzgom to the opendatahub-io members list

---

config/opendatahub-io/org.yaml

Adding a new member to Model Registry repository access.
- [ x] New members have reviewed and acknowledged the Open Data Hub:
- [ x] [Enabled 2FA on their GitHub account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication)
- [x ] New members are added in alphabetical order
- [ x] Only one new member change per commit (if you add two members separate it in two commits
- [x ] For …

Add Steve Hawkins as member to Model Registry repo

---

config/opendatahub-io/org.yaml

clean up the ml dev experience sig and add harshad16 as chair

clean up the ml dev experience sig and add harshad16 as chair

---

config/opendatahub-io/org.yaml

add spolti to the org and sub team membership

---

config/opendatahub-io/org.yaml

New Joinee requesting access to opendatahub-io org as part of onboarding step
https://issues.redhat.com/browse/RHODS-12207

[RHODS-12207] Add moulalis to opendatahub-io org

---

config/opendatahub-io/org.yaml

Add Adriel and Jan to the ODH notebook teams

Add Adriel and Jan to the ODH Notebook teams

---

config/opendatahub-io/org.yaml

Add davidesalerno to opendatahub-io and model-serving

---

config/opendatahub-io/org.yaml

Add jedemo to dashboard developers

---

config/opendatahub-io/org.yaml

Fix dsalerno name

---

config/opendatahub-io/org.yaml

Add Adnan to the ODH Dashboard

---

.github/workflows/peribolos-check.yaml

Use DevOps token for peribolos check action

---

.github/workflows/peribolos-check.yaml

Reverts opendatahub-io/org-management#185

Revert "Use DevOps token for peribolos check action"

---

.github/workflows/peribolos.yaml
config/opendatahub-io/org.yaml

Add team for NASA Codeflare cluster access

---

.github/workflows/peribolos.yaml
config/opendatahub-io/org.yaml

Reverts opendatahub-io/org-management#184

Revert "Add team for NASA Codeflare cluster access"

---

config/opendatahub-io/org.yaml

Nasa cluster access

---

config/opendatahub-io/org.yaml

Adding @Sara4994 to the ODH member and Ai-Edge team member

Adding Sara4994 to Ai-edge team

---

config/opendatahub-io/org.yaml

Add jlalbertson to the org

---

config/opendatahub-io/org.yaml

Add harshad to nasa cluster access team

---

config/opendatahub-io/org.yaml

Add milite to org and nasa cluster access

---

config/opendatahub-io/org.yaml

Correcting the new repo name from caikit-tgis-client to [caikit-nlp-client](https://github.com/opendatahub-io/caikit-nlp-client).

Correcting the client repo name

---

config/opendatahub-io/org.yaml

Grant access for additional nasa users

---

config/opendatahub-io/org.yaml

I have joined the Operator Scrum Team on the RHODS/RHOAI Project.
@etirelli @VaishnaviHire
New Open Data Hub Member Requirements
New members have reviewed and acknowledged the Open Data Hub:
Code of Conduct
Contribution Guide
Community Membership Guidelines
Enabled 2FA on their GitHub account

Add mattmahoneyrh to the opendatahub-io members list

---

config/opendatahub-io/org.yaml

Add accorvin to nasa team

---

config/opendatahub-io/org.yaml

Add arslan2k12 to org and NASA access team

---

config/opendatahub-io/org.yaml

Add additional nasa team members

---

config/opendatahub-io/org.yaml

Add manilmaskey to org and nasa cluster access

---

config/opendatahub-io/org.yaml

Add @terrytangyuan to opendatahub-io

---

config/opendatahub-io/org.yaml

Add MarianMacik to org members and ai-edge maintainers

Add MarianMacik to org members and ai-edge maintainers

---

config/opendatahub-io/org.yaml

Add tonyxrmdavidson to the opendatahub-io maintainers list

---

config/opendatahub-io/org.yaml

Access required for syncing `CodeFlare Operator` and `KubeRay` Upstream <> Downstream repos. All sync PRs will be reviewed by an approver before merging.
@anishasthana @astefanutti 

Add ChristianZaccaria to Distributed Workloads Maintainers list

---

config/opendatahub-io/org.yaml

Remove winklerm from DW

---

config/opendatahub-io/org.yaml

Add oksanabaza to the opendatahub-io members list

---

config/opendatahub-io/org.yaml

MohammadiIram is part of RHOAI DevOps Team

Add MohammadiIram to the opendatahub-io members list

---

config/opendatahub-io/org.yaml

part of my onboarding as an intern working on the DevOps team
@riprasad 

Add alexxfan to opendatahub-io members list, DevOps team

---

config/opendatahub-io/org.yaml

Intern Onboarding process
@taneem-ibrahim

Add KillianGolds opendatahub-io, model-serving org as a member.

---

config/opendatahub-io/org.yaml

Add ashley-o0o to opendatahub-io

---

config/organization_members.yaml

Ruth Netser just started on Openshift AI Model Server team and needs to be added to the organization.
Add rnetser to the organization members

Add rnetser to opendatahub-io

---

config/organization_members.yaml

Add Saad Zaher (szaher) to Open Data Hub Org.

Add szaher to odh org

---

config/organization_members.yaml

See https://issues.redhat.com/browse/RHOAIENG-11770

Add csams as a member of the org

---

config/organization_members.yaml

I've joined the RHOAI TrustyAI team

Added dahlem to members

---

config/organization_members.yaml

Request to be added to the members list as per https://issues.redhat.com/browse/RHOAIENG-12907 
See above

Add Username

---

config/organization_members.yaml

---
adding myself as part of new hire onboarding

chore(onboarding): add andyatmiami to organization_members.yaml

---

config/organization_members.yaml

Adding UX members to the org for ease of tagging

Add UX members to organization_members.yaml

---

config/organization_members.yaml

Add akram organisation members
Adds akram organisation members
cc @dimakis

Add akram organisation members

---

config/organization_members.yaml

add prarit to the organization

---

config/organization_members.yaml

Needing to add in ET team members to help further drive the distributed Instructlab work
^^

adding octo ET members for distributed Ilab

---

config/organization_members.yaml

Adding the user resoluteCoder to the members list

added resoluteCoder to members list

---

config/organization_members.yaml

Add nicholasmakesthings (UX)

---

config/organization_members.yaml

Add tobiastal to opendatahub-io

Add tobiastal to opendatahub-io

---

config/organization_members.yaml

onboarding https://issues.redhat.com/browse/RHODS-13857

add ckhordiasma to members

---

config/organization_members.yaml

[RHOAIENG-15264] Adding Max Whittingham

---

config/organization_members.yaml

Remove gmarkley-VI from the org

---

config/organization_members.yaml

Add thom carlin
Add thom carlin as member

Add thom carlin

---

config/organization_members.yaml

Add individuals working on the feature store to the org

---

config/organization_members.yaml

add myself to the organization

Add ConorOM1 to opendatahub-io

---

config/organization_members.yaml

Update organization_members.yaml - add tdarby

---

config/organization_members.yaml

Update organization_members.yaml: add thatblindgeye

---

config/organization_members.yaml

Adding andresllh

---

config/organization_members.yaml

Adding Pat O'Connor to the org as per onboarding

Added Pat O Connor(chipspeak)

---

config/organization_members.yaml

Add pboyd to the list of organization members

chore: add pboyd to org members

---

config/organization_members.yaml

add adysenrothman to org members

add adysenrothman to org memebers

---

config/organization_members.yaml

Add Joseph Groenenboom <jgroenen@redhat.com> as a member.
Signed-off-by: Prarit Bhargava <prarit@redhat.com>

Add jgroenenboomj to organization members

---

config/organization_members.yaml

chore: add edobrove

---

config/organization_members.yaml

Adding GH username pmccarthy

---

config/organization_members.yaml

Adding GH user `carlkyrillos` to list of org members.

Adding carlkyrillos as org member

---

config/organization_members.yaml

Add syntaxsdev (Sidney Glinton) to org members list

Add syntaxsdev (Sidney Glinton) to org members

---

config/organization_members.yaml

following guidance for organization membership

adding brettmthompson as an organization member

---

config/organization_members.yaml

Removing user access for gregsheremeta

Removing user gregsheremeta

---

config/organization_members.yaml

Add 2000krysztof to org members

---

config/organization_members.yaml

Changes in Organization Members
* Add William Siqueira
* Remove Ramakrishna Pattnaik

Added William Siqueira and Removed Ramakrishna Pattnaik

---

config/organization_members.yaml

Adding [ntkathole](https://github.com/ntkathole) (Nikhil Kathole) to the org members.

Add Nikhil Kathole to the organization members

---

config/organization_members.yaml

Added myself to the org members

RHOAIENG-20389: add kryanbeane to org members

---

config/organization_members.yaml

Adding myself as part of new hire onboarding to opendatahub contributors list
cc: @dgutride @adnankhan666 @dpanshug

chore(oboarding): add claudialphonse78 to organization_members.yaml

---

config/organization_members.yaml

Remove adelton from the org

---

config/organization_members.yaml

Removing access for the employees who left the ODH organization
- Isabella do Amaral, 
- Tony davidson
- Andrea Lamparelli

Removing past employees from access; 

---

config/organization_members.yaml

Add 'jyejare' organization_members.yaml
'jyejare' has joined the RHOAI Feast project.

Add 'jyejare' organization_members.yaml

---

config/organization_members.yaml

Required to gain access to all git organizations.

add 'efazal' to organization_members.yaml

---

config/organization_members.yaml

Added myself (katieperry4) to the organization members list

Added katieperry4 to organization_members.yaml

---

config/organization_members.yaml

Adding my github user name to organization_members.yaml

Add dbasunag to organization_members.yaml

---

config/organization_members.yaml

Add member `eoinfennessy` to `config/organization_members.yaml`

Add eoinfennessy to org members

---

config/organization_members.yaml

Updated config with username

---

config/organization_members.yaml

Add kahowell to organization_members

---

config/organization_members.yaml

Adding myself as a member of the opendatahub-io org

Update organization_members.yaml to add nananosirova (myself) as a member

---

config/organization_members.yaml

added ikeola13 to organization members

added ikeola13 to organization members

---

config/organization_members.yaml

Add fege to the list of organization members

Add user fege

---

config/organization_members.yaml

Adding GH users `kramaranya`, `briangallagher` and `laurafitzgerald` to list of org members.

Add kramaranya, briangallagher and laurafitzgerald to organization_members

---

config/organization_members.yaml

ENG-22691: Adds 5 new members

---

config/organization_members.yaml

Add nhr as an org member

---

config/organization_members.yaml

Adding rroshan-rh (myself) to organization_members.yaml
Adding rroshan-rh (myself) to organization_members.yaml

Adding rroshan to organization_members.yaml

---

config/organization_members.yaml

Added my GitHub username (`saichandrapandraju`) to organization members list

Add saichandrapandraju to organization_members.yaml

---

config/organization_members.yaml

config: add pawelpaszki gh username to members

config: add pawelpaszki gh username to members

---

config/organization_members.yaml

Addition of Scott Froberg to the Opendatahub-io org.

Add Scott Froberg to org.

---

config/organization_members.yaml

Adding Gaurav Kamathe

---

config/organization_members.yaml

Part of the onboarding to OpenShift AI.

[RHOAIENG-23224] Add pierDipi to members

---

config/organization_members.yaml

Update organization_members.yaml - added abiazett

---

config/organization_members.yaml

Add jwm4 to organization_members.yaml

---

config/organization_admins.yaml
config/organization_members.yaml

part of user onboarding to RHOAI: https://issues.redhat.com/browse/RHOAIENG-20266

Add mafriedm

---

config/organization_members.yaml

Added myself as a team member.

RHOAIENG-24816: Added apaluska (Aniket Paluskar) as a new team member

---

config/organization_members.yaml

As per the onboarding process RHOAIENG-23692

Adding GowthamShanmugam as a member

---

config/organization_members.yaml

Adds mpandya15

---

config/organization_members.yaml

Added Amit Mendelevitch to org members

---

config/organization_members.yaml

Adding github username instead of Red Hat username

Rhoaieng 24816

---

config/organization_members.yaml

Adding my github user to organization_members.yaml

RHOAIENG-24620

---

config/organization_members.yaml

Remove dandawg from the org

---

config/organization_members.yaml

Request to add my GitHub username (schimuneck) to the opendatahub-io organization.

Add schimuneck to organization members

---

config/organization_members.yaml

My name is Ian Miller and I'm Software Engineer Intern at OpenShift AI RAG Team. Ask my manager @dimakis to add my profile @r3v5 to repo
